import React, { useEffect, useState } from 'react';

interface StoredFile {
  name: string;
  type: string;
  size: string;
  created: string;
}

const DataView: React.FC = () => {
  const [files, setFiles] = useState<StoredFile[]>([]);
  const [activeTab, setActiveTab] = useState<'files' | 'exports' | 'database'>('files');

  useEffect(() => {
    fetch('/storage')
      .then(() => {
        // Storage dir is served statically, no listing available; show placeholder
      })
      .catch(() => {});
  }, []);

  const tabs = [
    { id: 'files' as const, label: 'Generated Files' },
    { id: 'exports' as const, label: 'Exports' },
    { id: 'database' as const, label: 'Database' },
  ];

  return (
    <div style={{ height: '100%', overflowY: 'auto', padding: 32 }}>
      <div style={{ maxWidth: 1100, margin: '0 auto' }}>
        <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 20, color: 'var(--text-primary)' }}>
          Data & Storage
        </h2>

        {/* Tabs */}
        <div style={{
          display: 'flex',
          gap: 0,
          borderBottom: '1px solid var(--border-default)',
          marginBottom: 24,
        }}>
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                padding: '10px 20px',
                border: 'none',
                borderBottom: activeTab === tab.id ? '2px solid var(--text-primary)' : '2px solid transparent',
                background: 'transparent',
                color: activeTab === tab.id ? 'var(--text-primary)' : 'var(--text-tertiary)',
                fontWeight: 500,
                fontSize: 13,
                cursor: 'pointer',
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Content */}
        {activeTab === 'files' && (
          <div className="nyt-card">
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: 16,
            }}>
              <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' }}>
                Generated Files
              </h3>
              <span className="nyt-badge">{files.length} files</span>
            </div>
            {files.length === 0 ? (
              <div className="nyt-empty" style={{ padding: '48px 0' }}>
                <div className="nyt-empty__icon">▤</div>
                <div className="nyt-empty__text">No files generated yet</div>
                <div className="nyt-empty__sub">
                  Files generated by workflows (PDF reports, Excel exports, CSV) will appear here.
                </div>
              </div>
            ) : (
              <table className="nyt-table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Size</th>
                    <th>Created</th>
                  </tr>
                </thead>
                <tbody>
                  {files.map((f, i) => (
                    <tr key={i}>
                      <td style={{ fontWeight: 500 }}>{f.name}</td>
                      <td><span className="nyt-badge">{f.type}</span></td>
                      <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{f.size}</td>
                      <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{f.created}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}

        {activeTab === 'exports' && (
          <div className="nyt-card">
            <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 16, color: 'var(--text-primary)' }}>
              Available Export Formats
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 }}>
              {[
                { format: 'JSON', desc: 'Workflow definitions & agent results', ext: '.json' },
                { format: 'CSV', desc: 'Tabular data exports', ext: '.csv' },
                { format: 'Excel', desc: 'Spreadsheet reports', ext: '.xlsx' },
                { format: 'PDF', desc: 'Formatted report documents', ext: '.pdf' },
              ].map((e, i) => (
                <div
                  key={i}
                  className="nyt-card nyt-card--hoverable"
                  style={{ textAlign: 'center', padding: 20 }}
                >
                  <div style={{
                    fontSize: 24,
                    fontWeight: 700,
                    fontFamily: 'var(--font-mono)',
                    marginBottom: 8,
                    color: 'var(--text-primary)',
                  }}>
                    {e.ext}
                  </div>
                  <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{e.format}</div>
                  <div style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>{e.desc}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'database' && (
          <div className="nyt-card">
            <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 16, color: 'var(--text-primary)' }}>
              Database Tables
            </h3>
            <table className="nyt-table">
              <thead>
                <tr>
                  <th>Table</th>
                  <th>Description</th>
                  <th>Type</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { name: 'agents', desc: 'Registered AI agents', type: 'Core' },
                  { name: 'nodes', desc: 'Node type definitions', type: 'Core' },
                  { name: 'workflows', desc: 'Workflow definitions', type: 'Core' },
                  { name: 'workflow_runs', desc: 'Execution run history', type: 'Runtime' },
                  { name: 'workflow_logs', desc: 'Node execution logs', type: 'Runtime' },
                  { name: 'audit_logs', desc: 'Decision audit trail', type: 'Audit' },
                  { name: 'files', desc: 'Generated file metadata', type: 'Storage' },
                  { name: 'pending_approvals', desc: 'Human-in-loop items', type: 'Runtime' },
                ].map((t, i) => (
                  <tr key={i}>
                    <td style={{ fontFamily: 'var(--font-mono)', fontWeight: 500, color: 'var(--text-primary)' }}>
                      {t.name}
                    </td>
                    <td>{t.desc}</td>
                    <td><span className="nyt-badge">{t.type}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default DataView;
